name = "CLib"
prefix = ""
mainprefix = "tc"
author = "CLib Team"
sigversion = 3
version = "0.0.0" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "*.dll",
    "CLibDataBaseEditor.exe"
]
include = ["./include"]
