name = "CLib"
mainprefix = "tc"
modname = "CLib"
prefix = ""
author = "CLib Team"
sig_version = 3
version = "0.10.0.1030"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "*.dll",
    "CLibDataBaseEditor.exe"
]
include = ["./include"]

check = [
    "!version_set",
    "!comment_isdev"
]

postbuild = [
    "!version_unset",
    "!uncomment_isdev"
]

releasebuild = [
    "@zip @CLib"
]

key_name = "CLib_{{version}}"
authority = "CLib_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"

[scripts.version_set]
steps_linux = [
    "echo 'Setting version'",
    "sed -i -r -s 's/#define MAJOR 0/#define MAJOR {{semver.major}}/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define MINOR 0/#define MINOR {{semver.minor}}/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define PATCHLVL 0/#define PATCHLVL {{semver.patch}}/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define BUILD 0/#define BUILD {{semver.build}}/g' addons/CLib/CLib_Macros.hpp",
]
steps_windows = [
    "echo 'Setting version'",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define MAJOR 0', '#define MAJOR {{semver.major}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define MINOR 0', '#define MINOR {{semver.minor}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define PATCHLVL 0', '#define PATCHLVL {{semver.patch}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define BUILD 0', '#define BUILD {{semver.build}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true

[scripts.version_unset]
steps_linux = [
    "echo 'Unsetting version'",
    "sed -i -r -s 's/#define MAJOR {{semver.major}}/#define MAJOR 0/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define MINOR {{semver.minor}}/#define MINOR 0/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define PATCHLVL {{semver.patch}}/#define PATCHLVL 0/g' addons/CLib/CLib_Macros.hpp",
    "sed -i -r -s 's/#define BUILD {{semver.build}}/#define BUILD 0/g' addons/CLib/CLib_Macros.hpp",
]
steps_windows = [
    "echo 'Unsetting version'",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define MAJOR {{semver.major}}', '#define MAJOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define MINOR {{semver.minor}}', '#define MINOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define PATCHLVL {{semver.patch}}', '#define PATCHLVL 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define BUILD {{semver.build}}', '#define BUILD 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true

[scripts.comment_isdev]
steps_linux = [
    "echo 'Commenting out #define ISDEV'",
    "sed -i -r -s 's:#define ISDEV:// #define ISDEV:g' addons/CLib/CLib_Macros.hpp",
]
steps_windows = [
    "echo 'Commenting out #define ISDEV'",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '#define ISDEV', '// #define ISDEV' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true

[scripts.uncomment_isdev]
steps_linux = [
    "echo 'Uncommenting #define ISDEV'",
    "sed -i -r -s 's:// #define ISDEV:#define ISDEV:g' addons/CLib/CLib_Macros.hpp",
]
steps_windows = [
    "echo 'Uncommenting #define ISDEV'",
    "powershell -Command foreach ($f in 'addons/CLib/CLib_Macros.hpp') {(Get-Content $f) -replace '// #define ISDEV', '#define ISDEV' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true
